"""Extended ondelete cascade for Person and subtypes

Revision ID: 4cbc99846039
Revises: c9fb820bf99a
Create Date: 2022-12-05 17:48:56.418248

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "4cbc99846039"
down_revision = "c9fb820bf99a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("partner_id_fkey", "partner", type_="foreignkey")
    op.create_foreign_key(
        None, "partner", "person", ["id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "person_organization_name_fkey", "person", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "person",
        "organization",
        ["organization_name"],
        ["name"],
        ondelete="SET NULL",
    )
    op.drop_constraint("student_id_fkey", "student", type_="foreignkey")
    op.create_foreign_key(
        None, "student", "person", ["id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("supervisor_id_fkey", "supervisor", type_="foreignkey")
    op.create_foreign_key(
        None, "supervisor", "person", ["id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "supervisor", type_="foreignkey")
    op.create_foreign_key(
        "supervisor_id_fkey", "supervisor", "person", ["id"], ["id"]
    )
    op.drop_constraint(None, "student", type_="foreignkey")
    op.create_foreign_key(
        "student_id_fkey", "student", "person", ["id"], ["id"]
    )
    op.drop_constraint(None, "person", type_="foreignkey")
    op.create_foreign_key(
        "person_organization_name_fkey",
        "person",
        "organization",
        ["organization_name"],
        ["name"],
    )
    op.drop_constraint(None, "partner", type_="foreignkey")
    op.create_foreign_key(
        "partner_id_fkey", "partner", "person", ["id"], ["id"]
    )
    # ### end Alembic commands ###
