"""Map ProjectComponents in hierarchy

Revision ID: 4ce9ca3d32ee
Revises: 148f021faa58
Create Date: 2023-05-03 18:13:01.554168

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4ce9ca3d32ee"
down_revision = "148f021faa58"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_component",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("power", sa.Float(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("blackout_threshold", sa.Float(), nullable=True),
        sa.Column("injection_price", sa.Float(), nullable=True),
        sa.Column("efficiency", sa.Float(), nullable=False),
        sa.Column("fuel_cost", sa.Float(), nullable=False),
        sa.Column("overheats", sa.Boolean(), nullable=False),
        sa.Column("overheating_time", sa.Float(), nullable=True),
        sa.Column("cooldown_time", sa.Float(), nullable=True),
        sa.Column("capacity", sa.Float(), nullable=False),
        sa.Column(
            "battery_type",
            postgresql.ENUM(name="batterytype", create_type=False),
            nullable=False,
        ),
        sa.Column("base_soc", sa.Float(), nullable=False),
        sa.Column("min_soc", sa.Float(), nullable=False),
        sa.Column("max_soc", sa.Float(), nullable=False),
        sa.Column("is_critical", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("energy_project_component")
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "user",
        "password",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_table(
        "energy_project_component",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "project_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "power",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_primary", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "price",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "blackout_threshold",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "injection_price",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "efficiency",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fuel_cost",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "overheats", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "overheating_time",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cooldown_time",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "capacity",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "battery_type",
            postgresql.ENUM("LITHIUM_ION", "LEAD_ACID", name="batterytype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "base_soc",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "min_soc",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "max_soc",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_critical", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name="energy_project_component_project_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="energy_project_component_pkey"),
    )
    op.drop_table("project_component")
    # ### end Alembic commands ###
