"""Extended ondelete cascade for Person and subtypes (fixof fix). Added project description.

Revision ID: 8a171ef323b7
Revises: 4cbc99846039
Create Date: 2022-12-05 18:03:42.928435

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a171ef323b7"
down_revision = "4cbc99846039"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("description", sa.Text(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "description")
    # ### end Alembic commands ###
