"""Extended ondelete cascade for project objects

Revision ID: b767d3d57393
Revises: d2a8ad152673
Create Date: 2022-12-05 17:29:39.864446

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b767d3d57393"
down_revision = "d2a8ad152673"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "address_location_id_fkey", "address", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "address",
        "location",
        ["location_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "coordinates_location_id_fkey", "coordinates", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "coordinates",
        "location",
        ["location_id"],
        ["project_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "project_contact_project_id_fkey",
        "project_contact",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "project_contact",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "project_partners_project_id_fkey",
        "project_partners",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "project_partners",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "project_sdg_project_id_fkey", "project_sdg", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "project_sdg",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "project_student_project_id_fkey",
        "project_student",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "project_student",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "project_super_project_id_fkey", "project_super", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "project_super",
        "project",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_super", type_="foreignkey")
    op.create_foreign_key(
        "project_super_project_id_fkey",
        "project_super",
        "project",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "project_student", type_="foreignkey")
    op.create_foreign_key(
        "project_student_project_id_fkey",
        "project_student",
        "project",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "project_sdg", type_="foreignkey")
    op.create_foreign_key(
        "project_sdg_project_id_fkey",
        "project_sdg",
        "project",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "project_partners", type_="foreignkey")
    op.create_foreign_key(
        "project_partners_project_id_fkey",
        "project_partners",
        "project",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "project_contact", type_="foreignkey")
    op.create_foreign_key(
        "project_contact_project_id_fkey",
        "project_contact",
        "project",
        ["project_id"],
        ["id"],
    )
    op.drop_constraint(None, "coordinates", type_="foreignkey")
    op.create_foreign_key(
        "coordinates_location_id_fkey",
        "coordinates",
        "location",
        ["location_id"],
        ["project_id"],
    )
    op.drop_constraint(None, "address", type_="foreignkey")
    op.create_foreign_key(
        "address_location_id_fkey",
        "address",
        "location",
        ["location_id"],
        ["project_id"],
    )
    # ### end Alembic commands ###
