"""Add project creator foreign key

Revision ID: bf9413ea8f20
Revises:
Create Date: 2022-11-21 20:30:48.999925

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf9413ea8f20"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_role",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_role_id"],
            ["user_role.id"],
        ),
    )
    op.drop_table("users_roles")
    op.add_column(
        "project", sa.Column("creator_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "project", "user", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_column("project", "creator_id")
    op.create_table(
        "users_roles",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "user_role_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="users_roles_user_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_role_id"],
            ["user_role.id"],
            name="users_roles_user_role_id_fkey",
        ),
    )
    op.drop_table("users_role")
    # ### end Alembic commands ###
