"""Extended ondelete cascade for project objects (fix)

Revision ID: c9fb820bf99a
Revises: b767d3d57393
Create Date: 2022-12-05 17:38:34.731959

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9fb820bf99a"
down_revision = "b767d3d57393"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "location_project_id_fkey", "location", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "location", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "location", type_="foreignkey")
    op.create_foreign_key(
        "location_project_id_fkey",
        "location",
        "project",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
