"""Added delete cascade to users and roles

Revision ID: e9923e4262fc
Revises: bf9413ea8f20
Create Date: 2022-11-22 18:24:16.314344

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "e9923e4262fc"
down_revision = "bf9413ea8f20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "users_role_user_id_fkey", "users_role", type_="foreignkey"
    )
    op.drop_constraint(
        "users_role_user_role_id_fkey", "users_role", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "users_role",
        "user_role",
        ["user_role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "users_role", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_role", type_="foreignkey")
    op.drop_constraint(None, "users_role", type_="foreignkey")
    op.create_foreign_key(
        "users_role_user_role_id_fkey",
        "users_role",
        "user_role",
        ["user_role_id"],
        ["id"],
    )
    op.create_foreign_key(
        "users_role_user_id_fkey", "users_role", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
